/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SampleWebComponents {
        "name": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSampleWebComponentsElement extends Components.SampleWebComponents, HTMLStencilElement {
    }
    var HTMLSampleWebComponentsElement: {
        prototype: HTMLSampleWebComponentsElement;
        new (): HTMLSampleWebComponentsElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sample-web-components": HTMLSampleWebComponentsElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SampleWebComponents {
        "name"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sample-web-components": SampleWebComponents;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sample-web-components": LocalJSX.SampleWebComponents & JSXBase.HTMLAttributes<HTMLSampleWebComponentsElement>;
        }
    }
}
